In [13]:
#Importing PyTorch
import torch

In [24]:
#Creating random inputs
torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))
print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [25]:
#Activation function
def activation(x):
    return 1/(1+torch.exp(-x))

In [27]:
#Calculate the output
output = activation(torch.mm(features, weights.view(5,1)) + bias)
print(output)

tensor([[0.1595]])
