In [4]:
#Importing PyTorch
import torch

In [5]:
#Creating random inputs
torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))
print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [6]:
#Activation function
def activation(x):
    return 1/(1+torch.exp(-x))

In [7]:
#Calculate the output
output = activation(torch.mm(features, weights.view(5,1)) + bias)
print(output)

tensor([[0.1595]])


In [10]:
#Building multiple layers
n_inputs = 3
n_hidden = 2
n_output = 1

torch.manual_seed(7)

F = torch.randn(1,3)
W1 = torch.randn(n_inputs, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [11]:
#Calculating the output
h = activation(torch.mm(F, W1) + B1)
out = activation(torch.mm(h, W2) + B2)
print(out)

tensor([[0.3171]])
